### ISSUE TITLE
Make pre-built artifacts available via github workflows

### ISSUE THREAD

**Issue by whot** [hidutils/hid-recorder#29]
Somewhat related to #25. Ideally we'd have a simple URL for users to download the static build of hid-recorder directly from github artifacts. This way they don't have to care about dependencies and cargo's install behaviour (into $HOME) that will fail when running as root.

**Comment by timr1234** [comment]
The readme reflects that this should be in place, but I see no releases after July 19th and therefore no pre-built binaries.

**Comment by whot** [comment]
huh, good point. I'll get a release out next week now that hidreport/hut are settling for the new/updated APIs. Thanks for the reminder.

**Comment by whot** [comment]
alright, 0.4.0 is out and the `hid-recorder.zip` is attached to the [release](https://github.com/hidutils/hid-recorder/releases/tag/0.4.0) so this worked as expected. :tada:
